[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "node dist/main"
healthcheckPath = "/api/v1/health/live"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
